name: Basic tests

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: False
      matrix:
        command:
          - pytest
          - find tests/CI -name '*.sh' -print0 | xargs -0 -n1 shellcheck --external-sources;
          - ./runPylint.sh
          - CHECK=pylintPY3K ./runPylint.sh
          - |
            if [[ "${REFERENCE_BRANCH}" != "" ]]; then
                git remote add GH https://github.com/DIRACGrid/Pilot.git
                git fetch --no-tags GH ${REFERENCE_BRANCH}
                git branch -vv
                git diff -U0 GH/${REFERENCE_BRANCH} | pycodestyle --diff;
            fi
        python: 
          # - 2.6.9
          - 2.7.5
          - 2.7.13
          - 3.6.8

    steps:
    - uses: actions/checkout@v1
    - name: Prepare environment
      run: |
        conda config --set add_pip_as_python_dependency false
        conda create -c conda-forge -c free -n python_${{ matrix.python }} python=${{ matrix.python }}
        source "${CONDA}/bin/activate"
        conda activate python_${{ matrix.python }}
        conda install pytest pytest-mock pylint autopep8  mock requests

        if [[ "${{ matrix.python }}" == "3.6.8" ]]
        then
            pip install stomp.py
        else
            pip install caniusepython3 stomp.py
        fi

        
    - name: Run tests
      run: |
        if [[ "${{ matrix.python }}" == "3.6.8" ]] && [[ "${{ matrix.command }}" == "CHECK=pylintPY3K ./runPylint.sh" ]]
        then
            echo "skipped"
        else
            source "${CONDA}/bin/activate"
            conda activate python_${{ matrix.python }}
            set -euxo pipefail
            export PYTHONPATH=${PWD%/*}
            ${{ matrix.command }}
        fi
      env:
        REFERENCE_BRANCH: ${{ github['base_ref'] || github['head_ref'] }}