name: Nightly

on: 
  schedule:
    # every night at midnight
    - cron:  '0 0 * * *'


jobs:
  # uploading master and devel tarballs to web server, for use in subsequent tests
  upload:
    runs-on: ubuntu-latest
    if: github.repository == 'DIRACGrid/Pilot'

    strategy:
      fail-fast: False
      matrix:
        branch:
          - master
          - devel

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - name: upload
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login docker.pkg.github.com --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker pull docker.pkg.github.com/diracgrid/management/dirac-distribution:latest
          contID=$(docker run -dt docker.pkg.github.com/diracgrid/management/dirac-distribution:latest)
          docker cp tests/pilot.json ${contID}:.
          docker exec ${contID} bash -c \
          "sed -i 's/uploaduser/${{ secrets.KRB_USERNAME }}/g' pilot_tarball_upload.sh && "\
          "cat pilot_tarball_upload.sh && "\
          "echo ${{ secrets.KRB_PASSWORD }} | kinit ${{ secrets.KRB_USERNAME }}@CERN.CH  && "\
          "echo readyToUpload && "\
          "export USER=${{ secrets.KRB_USERNAME }} && "\
          "echo reallyReadyToUpload && "\
          "./pilot_tarball_upload.sh ${{ matrix.branch }}""
